//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proga
{
    using System;
    using System.Collections.Generic;
    
    public partial class supply
    {
        public int ID { get; set; }
        public Nullable<int> ID_inventory { get; set; }
        public Nullable<int> ID_provider { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual inventory inventory { get; set; }
        public virtual Providers Providers { get; set; }
    }
}
